# ui/tabs/ai_report_generator.py
"""
AI Report Generator — institutional-grade, LLM-powered, 100% real data.
All report content is generated by the configured LLM using live portfolio
positions, real EODHD market data, and actual PE company metrics.
"""
import streamlit as st
import pandas as pd
import numpy as np
import json
import plotly.graph_objects as go
from datetime import datetime

from config import config
from services.data_fetcher import (
    pro_get_real_time_data,
    pro_get_historical_data,
    pro_get_fundamental_data,
    pro_get_news,
    get_market_data_yfinance,
)
from analysis.reporting import (
    generate_investment_memo,
    generate_board_pack_content,
    generate_equity_research_report_content,
)

# ─────────────────────────────────────────────────────────────────────────────
# Report catalogue
# ─────────────────────────────────────────────────────────────────────────────

REPORT_CATALOG = {
    "Investment Memorandum": {
        "icon": "📋",
        "description": "Full PE investment memo — MOIC, IRR, investment thesis, and committee-ready recommendation.",
        "sections": ["Executive Summary", "Investment Thesis", "Financial Performance",
                     "Value Creation Initiatives", "Risk Assessment",
                     "Exit Strategy", "Recommendations"],
        "data": ["PE Portfolio", "HF Positions"],
        "requires_pe": True,
        "requires_equity": False,
    },
    "Board Pack Commentary": {
        "icon": "🗂️",
        "description": "Executive board materials with KPI progression, operational highlights, and forward guidance.",
        "sections": ["Executive Dashboard", "Financial Performance", "Operational Highlights",
                     "Market Position", "Strategic Initiatives", "Risk Management", "Forward Guidance"],
        "data": ["PE Portfolio", "KPI History"],
        "requires_pe": True,
        "requires_equity": False,
    },
    "Quarterly Investor Report": {
        "icon": "📊",
        "description": "Comprehensive LP-level fund report covering performance, activity, and outlook.",
        "sections": ["Executive Summary", "Portfolio Performance", "Market Commentary",
                     "Investment Activity", "Exit Activity", "Outlook & Strategy"],
        "data": ["HF Positions (live prices)", "PE Portfolio"],
        "requires_pe": False,
        "requires_equity": False,
    },
    "Equity Research Report": {
        "icon": "🔬",
        "description": "Sell-side quality deep-dive using real EODHD fundamentals and price history.",
        "sections": ["Investment Summary", "Business Overview", "Financial Analysis",
                     "Valuation", "Risks & Catalysts", "Rating & Price Target"],
        "data": ["EODHD Fundamentals", "Historical Prices"],
        "requires_pe": False,
        "requires_equity": True,
    },
    "Risk & Exposure Report": {
        "icon": "⚠️",
        "description": "Concentration (HHI), sector exposure, drawdown, and stress-test scenarios.",
        "sections": ["Risk Overview", "Concentration Analysis", "Sector Exposure",
                     "Market Risk Metrics", "Liquidity Profile", "Stress Test Scenarios"],
        "data": ["HF Positions (live prices)"],
        "requires_pe": False,
        "requires_equity": False,
    },
    "Performance Attribution": {
        "icon": "📈",
        "description": "Decompose returns by security, weight, and timing across all held positions.",
        "sections": ["Performance Summary", "Top Contributors", "Detractors",
                     "Diversification Assessment", "Risk-Adjusted Commentary", "Recommendations"],
        "data": ["HF Positions (live prices)"],
        "requires_pe": False,
        "requires_equity": False,
    },
    "Market Sentiment Summary": {
        "icon": "🌍",
        "description": "Real-time news headlines and live price signals synthesised into actionable macro commentary.",
        "sections": ["Market Overview", "News Sentiment", "Price Action Analysis",
                     "Sector Themes", "Key Risks & Tailwinds", "Investment Implications"],
        "data": ["EODHD News Feed", "Live Prices"],
        "requires_pe": False,
        "requires_equity": False,
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Data helpers
# ─────────────────────────────────────────────────────────────────────────────

def _hf_portfolio_df(trading_engine, api_key: str) -> pd.DataFrame:
    """Build a live-priced DataFrame from the trading engine's positions."""
    if not trading_engine or not getattr(trading_engine, "positions", None):
        return pd.DataFrame()
    rows = []
    for symbol, pos in trading_engine.positions.items():
        qty = pos.get("quantity", 0)
        avg = pos.get("avg_price", 0)
        live = pro_get_real_time_data(symbol, api_key) or {}
        price = live.get("close") or avg
        mv = qty * price
        pnl = (price - avg) * qty
        ret_pct = ((price - avg) / avg * 100) if avg else 0.0
        rows.append({
            "Symbol": symbol,
            "Quantity": qty,
            "Avg Price": avg,
            "Current Price": price,
            "Market Value": mv,
            "Unrealized PNL": pnl,
            "Return %": ret_pct,
        })
    return pd.DataFrame(rows)


def _risk_stats(df: pd.DataFrame) -> dict:
    """Compute portfolio-level risk metrics from a live-priced positions frame."""
    if df.empty:
        return {}
    total_mv = df["Market Value"].sum()
    if total_mv == 0:
        return {}
    df = df.copy()
    df["Weight"] = df["Market Value"] / total_mv
    hhi = float((df["Weight"] ** 2).sum())
    top3 = df.nlargest(3, "Market Value")["Symbol"].tolist()
    total_pnl = df["Unrealized PNL"].sum()
    cost_basis = total_mv - total_pnl
    pnl_pct = (total_pnl / cost_basis * 100) if cost_basis else 0.0
    return {
        "total_market_value": total_mv,
        "total_pnl": total_pnl,
        "total_pnl_pct": pnl_pct,
        "hhi": hhi,
        "max_weight_pct": float(df["Weight"].max() * 100),
        "top3_positions": top3,
        "n_positions": len(df),
        "df_with_weights": df,
    }


def _fetch_news_text(symbols: list, api_key: str, per_symbol: int = 3) -> str:
    """Return a formatted string of recent headlines for the given symbols."""
    lines = []
    for sym in symbols[:5]:
        articles = pro_get_news(sym, api_key) or []
        for art in articles[:per_symbol]:
            if isinstance(art, dict) and art.get("title"):
                lines.append(f"[{sym}] {art['title']} — {art.get('date', '')}")
    return "\n".join(lines) if lines else "No recent news available."


# ─────────────────────────────────────────────────────────────────────────────
# LLM report builders (real data, no placeholders)
# ─────────────────────────────────────────────────────────────────────────────

def _llm_call(llm, prompt: str, label: str) -> str:
    try:
        response = llm.invoke(prompt)
        return response.content
    except Exception as exc:
        return f"⚠️ {label} generation failed: {exc}"


def _build_quarterly_report(llm, pe_portfolio, hf_df: pd.DataFrame,
                             period: str, audience: str, detail: str,
                             instructions: str) -> str:
    pe_block = ""
    if pe_portfolio:
        invested = sum(c.get("Invested Capital (M)", 0) for c in pe_portfolio)
        value = sum(c.get("Current Valuation (M)", 0) for c in pe_portfolio)
        avg_moic = (value / invested) if invested else 0
        avg_irr = (sum(c.get("IRR (%)", 0) for c in pe_portfolio) / len(pe_portfolio))
        names = ", ".join(c.get("Company Name", "?") for c in pe_portfolio)
        pe_block = (
            f"Private Equity Portfolio:\n"
            f"  Companies ({len(pe_portfolio)}): {names}\n"
            f"  Total Invested Capital: ${invested:.1f}M\n"
            f"  Current Portfolio Value: ${value:.1f}M\n"
            f"  Unrealised Gain: ${value - invested:.1f}M\n"
            f"  Average MOIC: {avg_moic:.2f}x\n"
            f"  Average IRR: {avg_irr:.1f}%\n"
        )

    hf_block = ""
    if not hf_df.empty:
        total_mv = hf_df["Market Value"].sum()
        total_pnl = hf_df["Unrealized PNL"].sum()
        best = hf_df.loc[hf_df["Return %"].idxmax()]
        worst = hf_df.loc[hf_df["Return %"].idxmin()]
        positions_str = hf_df[["Symbol", "Current Price", "Return %", "Market Value"]].to_string(index=False)
        hf_block = (
            f"\nHedge Fund Portfolio:\n"
            f"  Positions ({len(hf_df)}): {', '.join(hf_df['Symbol'].tolist())}\n"
            f"  Total Market Value: ${total_mv:,.0f}\n"
            f"  Total Unrealised PNL: ${total_pnl:+,.0f}\n"
            f"  Best Performer: {best['Symbol']} ({best['Return %']:+.1f}%)\n"
            f"  Worst Performer: {worst['Symbol']} ({worst['Return %']:+.1f}%)\n\n"
            f"  Position Detail:\n{positions_str}\n"
        )

    prompt = f"""You are a Senior Fund Manager writing a {period} Quarterly Investor Report.
Target Audience: {audience}
Detail Level: {detail}
{f"Special Instructions: {instructions}" if instructions else ""}

LIVE FUND DATA:
{pe_block}{hf_block}

Write a comprehensive Quarterly Investor Report with these sections:
1. Executive Summary
2. Portfolio Performance (quote exact numbers from the data above)
3. Market Commentary
4. Investment Activity
5. Outlook & Strategy

Be specific and professional. Reference real positions and real numbers. No placeholders.
"""
    return _llm_call(llm, prompt, "Quarterly Investor Report")


def _build_risk_report(llm, hf_df: pd.DataFrame, stats: dict,
                       period: str, audience: str, detail: str,
                       instructions: str) -> str:
    if hf_df.empty:
        return "No HF positions available. Add positions via the Trading Engine."

    df_w = stats.get("df_with_weights", hf_df).copy()
    df_w["Weight %"] = (df_w.get("Weight", 0) * 100).round(2)
    table = df_w[["Symbol", "Current Price", "Market Value", "Weight %",
                  "Return %", "Unrealized PNL"]].to_string(index=False)

    prompt = f"""You are a Chief Risk Officer preparing a Risk & Exposure Report.
Target Audience: {audience}
Detail Level: {detail}
{f"Special Instructions: {instructions}" if instructions else ""}

PORTFOLIO RISK DATA ({period}):
  Total Portfolio Value:  ${stats['total_market_value']:,.0f}
  Number of Positions:   {stats['n_positions']}
  Concentration (HHI):   {stats['hhi']:.4f}  (1.0 = single stock, 0.0 = perfectly equal)
  Largest Position:      {stats['max_weight_pct']:.1f}% of portfolio
  Top 3 Holdings:        {", ".join(stats['top3_positions'])}
  Total Unrealised PNL:  ${stats['total_pnl']:+,.0f} ({stats['total_pnl_pct']:+.1f}%)

POSITION BREAKDOWN:
{table}

Write a detailed Risk & Exposure Report covering:
1. Executive Risk Overview (overall portfolio risk posture)
2. Concentration Risk Analysis (interpret HHI and top-3 dominance with real numbers)
3. Market Risk Assessment (comment on position-level Return % dispersion)
4. Liquidity Profile (large positions vs. small, any illiquidity concern)
5. Stress Test Scenarios — propose 3 realistic macro scenarios with estimated P&L impact using actual position sizes
6. Risk Mitigation Recommendations

Use only the data provided. Be precise and actionable. No filler.
"""
    return _llm_call(llm, prompt, "Risk & Exposure Report")


def _build_attribution_report(llm, hf_df: pd.DataFrame, period: str,
                               audience: str, detail: str,
                               instructions: str) -> str:
    if hf_df.empty:
        return "No HF positions available for attribution analysis."

    df = hf_df.copy()
    total_mv = df["Market Value"].sum()
    df["Weight %"] = (df["Market Value"] / total_mv * 100).round(2)
    df["Contribution %"] = (df["Weight %"] / 100 * df["Return %"]).round(4)
    df_sorted = df.sort_values("Contribution %", ascending=False)

    table = df_sorted[["Symbol", "Weight %", "Return %",
                        "Contribution %", "Unrealized PNL"]].to_string(index=False)
    weighted_ret = (df["Return %"] * df["Weight %"] / 100).sum()
    total_pnl = df["Unrealized PNL"].sum()

    prompt = f"""You are a Senior Portfolio Analyst preparing a Performance Attribution Report.
Target Audience: {audience}
Detail Level: {detail}
{f"Special Instructions: {instructions}" if instructions else ""}

ATTRIBUTION DATA — {period}:
  Portfolio Weighted Return: {weighted_ret:+.2f}%
  Total Unrealised PNL:      ${total_pnl:+,.0f}
  Number of Positions:       {len(df)}

Position-Level Attribution (sorted by contribution):
{table}

Write a detailed Performance Attribution Analysis:
1. Performance Summary (headline weighted return, total P&L)
2. Top Contributors — explain each top-3 position's outsized return using the actual numbers
3. Key Detractors — explain underperformance drivers and forward outlook
4. Concentration & Diversification Assessment (weight distribution commentary)
5. Risk-Adjusted Return Commentary (note: no Sharpe benchmark available; estimate qualitatively)
6. Actionable Recommendations to improve attribution going forward

Use only the real data provided. No placeholders or generic statements.
"""
    return _llm_call(llm, prompt, "Performance Attribution")


def _build_market_sentiment(llm, hf_df: pd.DataFrame, api_key: str,
                             period: str, audience: str, detail: str,
                             instructions: str) -> str:
    symbols = hf_df["Symbol"].tolist() if not hf_df.empty else []
    news_text = _fetch_news_text(symbols, api_key)

    prices_block = ""
    if not hf_df.empty:
        prices_block = hf_df[["Symbol", "Current Price", "Return %"]].to_string(index=False)

    prompt = f"""You are a Chief Market Strategist preparing a Market Sentiment Summary.
Target Audience: {audience}
Detail Level: {detail}
{f"Special Instructions: {instructions}" if instructions else ""}

LIVE PORTFOLIO POSITIONS:
{prices_block if prices_block else "No positions loaded."}

RECENT NEWS HEADLINES (from EODHD):
{news_text}

Write a Market Sentiment Summary covering:
1. Overall Market Overview (macro regime, risk-on/risk-off)
2. News Sentiment Analysis — interpret each headline group and infer sector/company sentiment
3. Price Action Analysis — comment on the Return % data above; which positions signal momentum vs. fatigue
4. Key Risks & Tailwinds for the current portfolio
5. Investment Implications — specific, actionable guidance

Reference the real headlines and real prices above. No generic market commentary.
"""
    return _llm_call(llm, prompt, "Market Sentiment Summary")


def _dispatch_report(report_type: str, params: dict, pe_portfolio,
                     trading_engine, llm) -> str:
    """Route to the correct report builder with all real data injected."""
    api_key = config.get_eodhd_api_key()
    period = params["period"]
    audience = params["audience"]
    detail = params["detail"]
    instructions = params.get("instructions", "")

    hf_df = _hf_portfolio_df(trading_engine, api_key)

    if report_type == "Investment Memorandum":
        if not pe_portfolio:
            return "No PE portfolio companies available. Please add companies first."
        company_name = params.get("selected_company")
        company_data = next(
            (c for c in pe_portfolio if c.get("Company Name") == company_name),
            pe_portfolio[0],
        )
        return generate_investment_memo(llm, company_data, hf_df)

    elif report_type == "Board Pack Commentary":
        if not pe_portfolio:
            return "No PE portfolio companies available."
        company_name = params.get("selected_company")
        company_data = next(
            (c for c in pe_portfolio if c.get("Company Name") == company_name),
            pe_portfolio[0],
        )
        kpi_history = company_data.get("KPI History", pd.DataFrame())
        return generate_board_pack_content(llm, company_data, kpi_history)

    elif report_type == "Quarterly Investor Report":
        return _build_quarterly_report(llm, pe_portfolio, hf_df, period, audience, detail, instructions)

    elif report_type == "Equity Research Report":
        ticker = params.get("equity_ticker", "AAPL")
        year = params.get("equity_year", datetime.now().year - 1)
        with st.spinner(f"Fetching live fundamentals for {ticker} from EODHD…"):
            fundamentals = pro_get_fundamental_data(ticker, api_key)
            hist_df = pro_get_historical_data(ticker, api_key)
        if hist_df.empty:
            hist_df = get_market_data_yfinance(ticker, period="1y")
        if hist_df.empty:
            return f"Could not fetch market data for {ticker}. Check the ticker symbol."
        return generate_equity_research_report_content(llm, ticker, year, fundamentals, hist_df)

    elif report_type == "Risk & Exposure Report":
        stats = _risk_stats(hf_df)
        if not stats:
            return "No HF positions loaded. Add positions via the Trading Engine."
        return _build_risk_report(llm, stats["df_with_weights"], stats, period, audience, detail, instructions)

    elif report_type == "Performance Attribution":
        return _build_attribution_report(llm, hf_df, period, audience, detail, instructions)

    elif report_type == "Market Sentiment Summary":
        return _build_market_sentiment(llm, hf_df, api_key, period, audience, detail, instructions)

    return "Unknown report type."


# ─────────────────────────────────────────────────────────────────────────────
# UI
# ─────────────────────────────────────────────────────────────────────────────

def _status_bar(trading_engine, pe_portfolio, llm):
    """Live data status banner at the top of the tab."""
    hf_count = len(getattr(trading_engine, "positions", {}) or {})
    pe_count = len(pe_portfolio) if pe_portfolio else 0
    api_key = config.get_eodhd_api_key()
    api_ok = bool(api_key)
    llm_ok = bool(llm)

    cards = [
        ("HF POSITIONS", str(hf_count), "#42A5F5"),
        ("PE COMPANIES", str(pe_count), "#AB47BC"),
        ("MARKET DATA", "EODHD Live" if api_ok else "No API Key", "#26a69a" if api_ok else "#ef5350"),
        ("AI ENGINE", "Ready" if llm_ok else "Not Configured", "#26a69a" if llm_ok else "#ef5350"),
    ]
    cols = st.columns(4)
    for col, (label, value, color) in zip(cols, cards):
        col.markdown(
            f"""<div style="background:#1E2130;border-radius:8px;padding:0.65rem 1rem;text-align:center">
                <div style="color:#6B7280;font-size:0.68rem;letter-spacing:0.05em">{label}</div>
                <div style="color:{color};font-size:1.2rem;font-weight:700;margin-top:0.15rem">{value}</div>
            </div>""",
            unsafe_allow_html=True,
        )


def render_ai_report_generator_tab(trading_engine=None, pe_portfolio=None, llm=None):
    """World-class AI Report Generator — real data, LLM-powered, production-ready."""

    st.markdown("## 🤖 AI Report Generator")
    st.markdown(
        "*Institutional-grade reports generated live from your portfolio data, "
        "real EODHD market feeds, and Azure OpenAI.*"
    )

    if not llm:
        st.warning(
            "⚠️ LLM not configured. Set up Azure OpenAI in **API Configuration** to unlock report generation."
        )

    st.markdown("")
    _status_bar(trading_engine, pe_portfolio, llm)
    st.markdown("---")

    if "report_history" not in st.session_state:
        st.session_state.report_history = []

    main_tabs = st.tabs(["📋 Generate Report", "🕒 Report History", "📈 Usage Analytics"])

    # ── Generate Report ───────────────────────────────────────────────────────
    with main_tabs[0]:

        # Step 1 — report type
        st.markdown("#### 1 · Select Report Type")
        sel_col, info_col = st.columns([1, 1])

        with sel_col:
            selected_report = st.selectbox(
                "Report Type",
                list(REPORT_CATALOG.keys()),
                format_func=lambda k: f"{REPORT_CATALOG[k]['icon']}  {k}",
                label_visibility="collapsed",
            )

        meta = REPORT_CATALOG[selected_report]

        with info_col:
            st.markdown(
                f"""<div style="background:#1E2130;border-radius:8px;padding:0.8rem 1rem;
                             border-left:3px solid #42A5F5;">
                    <div style="color:#FAFAFA;font-weight:600;margin-bottom:0.25rem;">
                        {meta['icon']} {selected_report}
                    </div>
                    <div style="color:#D1D5DB;font-size:0.83rem;">{meta['description']}</div>
                    <div style="color:#6B7280;font-size:0.73rem;margin-top:0.35rem;">
                        📡 Data: {' · '.join(meta['data'])}
                    </div>
                </div>""",
                unsafe_allow_html=True,
            )

        st.markdown(
            "**Sections:** " + "  ·  ".join(f"`{s}`" for s in meta["sections"])
        )
        st.markdown("---")

        # Step 2 — configuration
        st.markdown("#### 2 · Configure")
        c1, c2, c3 = st.columns(3)
        with c1:
            report_period = st.selectbox(
                "Reporting Period",
                ["Current Quarter", "Last Quarter", "YTD", "Last 12 Months"],
            )
        with c2:
            audience = st.selectbox(
                "Target Audience",
                ["Board Members", "Investors / LPs", "Internal Team", "Regulators"],
            )
        with c3:
            detail_level = st.select_slider(
                "Detail Level",
                options=["Summary", "Standard", "Detailed", "Comprehensive"],
                value="Detailed",
            )

        # PE company selector
        selected_company = None
        if meta["requires_pe"]:
            if pe_portfolio:
                company_names = [c.get("Company Name", "Unknown") for c in pe_portfolio]
                selected_company = st.selectbox("Portfolio Company", company_names)
            else:
                st.info(
                    "No PE companies found. This report type requires PE portfolio data. "
                    "It will be generated with available HF data instead."
                )

        # Equity research fields
        equity_ticker = None
        equity_year = None
        if meta["requires_equity"]:
            eq1, eq2 = st.columns(2)
            with eq1:
                equity_ticker = (
                    st.text_input(
                        "Ticker Symbol",
                        value="AAPL",
                        help="Any EODHD-supported ticker, e.g. AAPL, TSLA, MSFT.US",
                    )
                    .upper()
                    .strip()
                )
            with eq2:
                equity_year = st.number_input(
                    "Fiscal Year",
                    min_value=2020,
                    max_value=datetime.now().year,
                    value=datetime.now().year - 1,
                )

        with st.expander("Advanced Options"):
            custom_instructions = st.text_area(
                "Custom Instructions for AI",
                placeholder=(
                    "e.g. 'Focus on ESG metrics', 'Highlight exit readiness', "
                    "'Include peer comparisons', 'Use conservative tone'…"
                ),
                height=80,
            )
            include_disclaimers = st.checkbox("Append Legal Disclaimer", value=True)
            mark_draft = st.checkbox("Mark Report as DRAFT", value=False)

        st.markdown("---")
        st.markdown("#### 3 · Generate")

        gen_btn_col, _ = st.columns([1, 2])
        with gen_btn_col:
            generate_btn = st.button(
                "🚀  Generate Report",
                type="primary",
                disabled=(llm is None),
                use_container_width=True,
            )

        if llm is None:
            st.caption("Configure Azure OpenAI in API Configuration to enable report generation.")

        if generate_btn and llm:
            params = {
                "period": report_period,
                "audience": audience,
                "detail": detail_level,
                "instructions": custom_instructions or "",
                "selected_company": selected_company,
                "equity_ticker": equity_ticker,
                "equity_year": equity_year,
            }

            with st.spinner(
                f"Generating **{selected_report}** — fetching live data and calling AI…"
            ):
                report_content = _dispatch_report(
                    selected_report, params, pe_portfolio, trading_engine, llm
                )

            # Watermark / disclaimer
            if mark_draft:
                report_content = "⚠️  DRAFT — NOT FOR DISTRIBUTION\n\n" + report_content
            if include_disclaimers:
                report_content += (
                    "\n\n---\n**Legal Disclaimer:** This report is generated using artificial intelligence "
                    "and real-time data for informational purposes only. It does not constitute investment "
                    "advice. Past performance is not indicative of future results. "
                    f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}"
                )

            word_count = len(report_content.split())

            # Save to session history
            st.session_state.report_history.append({
                "type": selected_report,
                "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "period": report_period,
                "audience": audience,
                "detail": detail_level,
                "content": report_content,
                "word_count": word_count,
            })

            # ── Display ────────────────────────────────────────────────────
            st.markdown("---")
            st.markdown(f"### {meta['icon']} {selected_report}")

            m1, m2, m3, m4 = st.columns(4)
            m1.metric("Words Generated", f"{word_count:,}")
            m2.metric("Report Sections", str(len(meta["sections"])))
            m3.metric("Period", report_period)
            m4.metric("Generated At", datetime.now().strftime("%H:%M:%S"))

            # Render the full report in a scrollable card
            st.markdown(
                f"""<div style="background:#1E2130;border-radius:10px;padding:1.5rem 2rem;
                             border:1px solid #2D3748;max-height:600px;overflow-y:auto;
                             font-family:Georgia,serif;line-height:1.7;color:#E2E8F0;
                             white-space:pre-wrap;">
{report_content}
                </div>""",
                unsafe_allow_html=True,
            )

            # ── Exports ─────────────────────────────────────────────────────
            st.markdown("#### 📥 Export Report")
            fname = (
                selected_report.lower()
                .replace(" ", "_")
                .replace("&", "and")
                .replace("/", "")
            )
            ts = datetime.now().strftime("%Y%m%d_%H%M")

            dl1, dl2, dl3 = st.columns(3)
            with dl1:
                st.download_button(
                    "⬇️ Download .txt",
                    report_content,
                    f"{fname}_{ts}.txt",
                    mime="text/plain",
                    use_container_width=True,
                )
            with dl2:
                md_content = (
                    f"# {selected_report}\n"
                    f"*{report_period} | {audience} | {detail_level}*\n\n"
                    + report_content
                )
                st.download_button(
                    "⬇️ Download .md",
                    md_content,
                    f"{fname}_{ts}.md",
                    mime="text/markdown",
                    use_container_width=True,
                )
            with dl3:
                json_payload = json.dumps(
                    {
                        "report_type": selected_report,
                        "generated_at": datetime.now().isoformat(),
                        "parameters": {
                            "period": report_period,
                            "audience": audience,
                            "detail_level": detail_level,
                        },
                        "content": report_content,
                        "word_count": word_count,
                    },
                    indent=2,
                )
                st.download_button(
                    "⬇️ Download .json",
                    json_payload,
                    f"{fname}_{ts}.json",
                    mime="application/json",
                    use_container_width=True,
                )

    # ── Report History ────────────────────────────────────────────────────────
    with main_tabs[1]:
        st.markdown("#### 🕒 Report History  *(this session)*")

        if not st.session_state.report_history:
            st.info("No reports generated yet. Generate your first report above.")
        else:
            for i, rep in enumerate(reversed(st.session_state.report_history)):
                real_idx = len(st.session_state.report_history) - i
                label = (
                    f"#{real_idx}  ·  {rep['type']}  ·  "
                    f"{rep['generated_at']}  ·  {rep.get('word_count', '?')} words"
                )
                with st.expander(label, expanded=(i == 0)):
                    h1, h2, h3 = st.columns(3)
                    h1.write(f"**Period:** {rep['period']}")
                    h2.write(f"**Audience:** {rep['audience']}")
                    h3.write(f"**Detail:** {rep['detail']}")

                    st.markdown(
                        f"""<div style="background:#1E2130;border-radius:8px;padding:1rem 1.5rem;
                                     border:1px solid #2D3748;max-height:400px;overflow-y:auto;
                                     font-family:Georgia,serif;line-height:1.7;color:#E2E8F0;
                                     white-space:pre-wrap;margin:0.5rem 0;">
{rep["content"]}
                        </div>""",
                        unsafe_allow_html=True,
                    )

                    safe_date = rep["generated_at"].replace(":", "").replace(" ", "_")
                    fname_h = (
                        rep["type"].lower()
                        .replace(" ", "_")
                        .replace("&", "and")
                        .replace("/", "")
                    )
                    st.download_button(
                        f"⬇️ Download Report #{real_idx}",
                        rep["content"],
                        f"{fname_h}_{safe_date}.txt",
                        use_container_width=True,
                        key=f"dl_hist_{i}",
                    )

    # ── Usage Analytics ───────────────────────────────────────────────────────
    with main_tabs[2]:
        st.markdown("#### 📈 Session Usage Analytics")

        if not st.session_state.report_history:
            st.info("Generate reports to see analytics.")
        else:
            history_df = pd.DataFrame(st.session_state.report_history)

            a1, a2, a3, a4 = st.columns(4)
            a1.metric("Total Reports", len(history_df))
            a2.metric("Total Words", f"{history_df['word_count'].sum():,}")
            a3.metric("Avg Words / Report", f"{int(history_df['word_count'].mean()):,}")
            a4.metric("Report Types", history_df["type"].nunique())

            # Report type frequency chart
            type_counts = history_df["type"].value_counts().reset_index()
            type_counts.columns = ["Report Type", "Count"]
            fig_types = go.Figure(
                go.Bar(
                    x=type_counts["Report Type"],
                    y=type_counts["Count"],
                    marker_color="#42A5F5",
                    text=type_counts["Count"],
                    textposition="outside",
                )
            )
            fig_types.update_layout(
                title="Reports by Type",
                paper_bgcolor="#0E1117",
                plot_bgcolor="#0E1117",
                font=dict(color="#FAFAFA"),
                margin=dict(l=0, r=0, t=40, b=0),
                height=280,
                showlegend=False,
            )
            fig_types.update_xaxes(gridcolor="#1E2130", tickangle=-20)
            fig_types.update_yaxes(gridcolor="#1E2130", dtick=1)
            st.plotly_chart(fig_types, use_container_width=True)

            # Word count over time
            fig_words = go.Figure(
                go.Scatter(
                    x=list(range(1, len(history_df) + 1)),
                    y=history_df["word_count"],
                    mode="lines+markers",
                    line=dict(color="#26a69a", width=2),
                    marker=dict(size=8, color="#26a69a"),
                    fill="tozeroy",
                    fillcolor="rgba(38,166,154,0.10)",
                    text=history_df["type"],
                    hovertemplate="Report #%{x}<br>%{text}<br>%{y:,} words<extra></extra>",
                )
            )
            fig_words.update_layout(
                title="Word Count per Report (chronological)",
                xaxis_title="Report #",
                yaxis_title="Words",
                paper_bgcolor="#0E1117",
                plot_bgcolor="#0E1117",
                font=dict(color="#FAFAFA"),
                margin=dict(l=0, r=0, t=40, b=0),
                height=240,
            )
            fig_words.update_xaxes(gridcolor="#1E2130", dtick=1)
            fig_words.update_yaxes(gridcolor="#1E2130")
            st.plotly_chart(fig_words, use_container_width=True)
